<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MdlRole', 'doctrine');

/**
 * BaseMdlRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $shortname
 * @property string $description
 * @property integer $sortorder
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getShortname()   Returns the current record's "shortname" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method integer getSortorder()   Returns the current record's "sortorder" value
 * @method MdlRole setId()          Sets the current record's "id" value
 * @method MdlRole setName()        Sets the current record's "name" value
 * @method MdlRole setShortname()   Sets the current record's "shortname" value
 * @method MdlRole setDescription() Sets the current record's "description" value
 * @method MdlRole setSortorder()   Sets the current record's "sortorder" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMdlRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdl_role');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shortname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sortorder', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}