<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/01 16:38:21
sfConfig::add(array(
  'mod_process_responses_enabled' => true,
  'mod_process_responses_view_class' => 'sfPHP',
));
