<?php

/**
 * MdlContextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdlContextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdlContextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MdlContext');
    }
    
    public function getContexts($fields,$value){

        $q = $this->createQuery("ctx")
                ->select("ctx.id")
                ->where("ctx.$fields = ?", $value)
                ->fetchArray();

        return $q;


    }
}