<?php

/**
 * MdlCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdlCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdlCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MdlCourse');
    }
    
    public function getCourse($id = null,$role=3){

        //$contexts = Doctrine::getTable("MdlContext")->getContexts("instaceid",);
        //$contexts = Doctrine::getTable("MdlContext")->getContexts("contextlevel",50);


        $q = $this->createQuery("c")
                    ->select("c.id,c.fullname,ctx.id,ra.id,u.id,u.username")
                    ->leftJoin("c.MdlContext ctx")
                    ->leftJoin("ctx.MdlRoleAssignments ra")
                    ->leftJoin("ra.MdlUser u")
                    ->where("ctx.contextlevel = 50")
                    ->andWhere("ra.roleid = ?",$role)
                    ->fetchArray();

       return $q;

    }

    public function getCourseByUser($user,$role=3){

        //$contexts = Doctrine::getTable("MdlContext")->getContexts("instaceid",);
        //$contexts = Doctrine::getTable("MdlContext")->getContexts("contextlevel",50);


        $q = $this->createQuery("c")
                    ->select("c.id,c.fullname,ctx.id,ra.id,u.id,u.username")
                    ->leftJoin("c.MdlContext ctx")
                    ->leftJoin("ctx.MdlRoleAssignments ra")
                    ->leftJoin("ra.MdlUser u")
                    ->where("ctx.contextlevel = 50")
                    ->andWhere("ra.roleid = ?",$role)
                    ->andWhere("u.id = ?", $user)
                    ->fetchArray();

       return $q;

    }
    
    public function isUserInCourse($course_id,$user_id,$role=5){
        $q = $this->createQuery("c")
                    ->select("c.id")
                    ->leftJoin("c.MdlContext ctx")
                    ->leftJoin("ctx.MdlRoleAssignments ra")
                    ->leftJoin("ra.MdlUser u")
                    ->where("ctx.contextlevel = 50")
                    ->andWhere("ra.roleid = ?",$role)
                    ->andWhere("u.id = ?", $user_id)
                    ->andWhere("ctx.instanceid = ?",$course_id)
                    ->fetchArray();
        
        if(count($q))
            return true;
        else
            return false;
    }
    
    public function getAllCourse($fields,$where=array()){
        
        $query = array();
        if(is_array($fields)){
            $list_fields = array();
            foreach($fields as $field){
                if(Doctrine::getTable("MdlCourse")->hasField($field)){
                    array_push($list_fields, $field);
                }
            }
            $query = $this->createQuery("c")
                    ->select(implode(",", $list_fields));    
        }elseif($fields == "*"){
            $query = $this->createQuery("c");   
        }
        
        if(is_array($where) && count($where) ){
            foreach($where as $k=>$v){
                foreach($v as $q=>$crt){
                    $query->andWhere(" $k $q ", $crt);
                }
            }
        }

       return $query->fetchArray();
        
    }
}