<?php

/**
 * MdlRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdlRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdlRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MdlRole');
    }
}