<?php

/**
 * MdlUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdlUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdlUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MdlUser');
    }
    
    public function getUsersByCourse($course,$role = array(5) ) {

        if( is_array($role) ){
            $param_role = implode(",", $role);
        }else{
            $param_role = $role;
        }


         $q = $this->createQuery("u")
                 ->select("u.id,u.username,u.firstname,u.lastname")
                 ->leftJoin("u.MdlRoleAssignments ra")
                 ->leftJoin("ra.MdlContext ctx")
                 ->leftJoin("ctx.MdlCourse c")
                 ->where("ctx.contextlevel = 50")
                 ->andWhere("ra.roleid IN (".$param_role.")")
                 ->andWhere("ctx.instanceid IN (".$course.")");


         $result = $q->fetchArray();

         return $result;

     }
     
}