<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/01 14:30:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vforge2',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
