<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/01 14:30:01
sfConfig::add(array(
  'app_nameApp' => 'SAVIOSurvey',
  'app_baseurl' => 'http://vmoodle-vforge/saviosurvey/frontapp.php',
  'app_URLMoodle' => 'http://vmoodle-vforge/',
  'app_mongodb_host' => 'localhost:27017',
  'app_mongodb_name' => 'surveysavio',
  'app_mongodb_user' => NULL,
  'app_mongodb_pass' => NULL,
));
