<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/31 16:15:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vforge2',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
