<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/05/31 16:15:52
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineformgenerator' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinecli' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionprofiler' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwidgetformdoctrinechoice' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'swift_doctrinespool' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sftesterdoctrine' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinegenerateadmintask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildformstask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedatadumptask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebasetask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedropdbtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedataloadtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinemigratetask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfformdoctrine' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinerecord' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfvalidatordoctrinechoice' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrineroutecollection' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineexception' => '/home/erick/Proyectos/saviosurvey/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',

  // project
  'mongomanager' => '/home/erick/Proyectos/saviosurvey/lib/mylib/MongoManager.php',
  'mongo_db' => '/home/erick/Proyectos/saviosurvey/lib/mylib/Mongodb.class.php',
  'things' => '/home/erick/Proyectos/saviosurvey/lib/mylib/Things.class.php',
  'baseform' => '/home/erick/Proyectos/saviosurvey/lib/form/BaseForm.class.php',

  // project_model
  'mdlcontexttable' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlContextTable.class.php',
  'mdluser' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlUser.class.php',
  'basemdlcourse' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/base/BaseMdlCourse.class.php',
  'basemdluser' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/base/BaseMdlUser.class.php',
  'basemdlrole' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/base/BaseMdlRole.class.php',
  'basemdlcontext' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/base/BaseMdlContext.class.php',
  'basemdlroleassignments' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/base/BaseMdlRoleAssignments.class.php',
  'mdlusertable' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlUserTable.class.php',
  'mdlcourse' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlCourse.class.php',
  'mdlroleassignmentstable' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlRoleAssignmentsTable.class.php',
  'mdlcontext' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlContext.class.php',
  'mdlrole' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlRole.class.php',
  'mdlroleassignments' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlRoleAssignments.class.php',
  'mdlroletable' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlRoleTable.class.php',
  'mdlcoursetable' => '/home/erick/Proyectos/saviosurvey/lib/model/doctrine/MdlCourseTable.class.php',

  // application
  'myuser' => '/home/erick/Proyectos/saviosurvey/apps/admin/lib/myUser.class.php',

  // modules
);
