<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/05/31 16:15:52
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'superuser',
        1 => 'admin',
      ),
    ),
  ),
);
