<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/31 16:15:52
sfConfig::add(array(
  'mod_process_responses_enabled' => true,
  'mod_process_responses_view_class' => 'sfPHP',
));
