<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/01 09:25:03
$this->security = array (
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'superuser',
        1 => 'admin',
      ),
    ),
  ),
);
